/*
 * OpenLOPD
 * Copyright (C) 2011  Eduardo L. García Glez <eduardo.l.g.g@gmail.com>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.jkingii.mail.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MailAccount entity primary key
 * @author Eduardo L. García Glez.
 */
@Embeddable
public class MailAccountPK implements Serializable {

    //<editor-fold defaultstate="collapsed" desc="Private Properties">
    @Basic(optional = false)
    @Column(nullable = false, length = 37)
    private String appId;
    @Basic(optional = false)
    @Column(nullable = false, length = 37)
    private String accountId;
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Constructors">
    /**
     * Default constructor.
     */
    public MailAccountPK() {
    }
    
    /**
     * Instance with all primary key properties.
     * @param appId app or owner identificator
     * @param accountId mail account unique id
     */
    public MailAccountPK(String appId, String accountId) {
        this.appId = appId;
        this.accountId = accountId;
    }
    //</editor-fold>

    /**
     * Gets mail account unique id
     * 
     * this is a id generates by jkingiiMail when new account is added.
     * 
     * @return mail account unique id
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * Set mail account unique id
     * 
     * this is a id generates by jkingiiMail when new account is added.
     * 
     * @param accountId mail account unique id.
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * Get de application/user identity.
     * 
     * An email account can belong to an application or an application user, 
     * here is added a unique identifier generated by jkingiiMail to identify 
     * the mail account uniquely.
     * 
     * @return mail account unique id
     */
    public String getAppId() {
        return appId;
    }

    /**
     * Set de application/user identity.
     * 
     * An email account can belong to an application or an application user, 
     * here is added a unique identifier generated by jkingiiMail to identify 
     * the mail account uniquely.
     * 
     * @param appId mail account unique id
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    //<editor-fold defaultstate="collapsed" desc="Defaulth Methods">
    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final MailAccountPK other = (MailAccountPK) obj;
        if ((this.appId == null) ? (other.appId != null) : !this.appId.equals(other.appId)) {
            return false;
        }
        if ((this.accountId == null) ? (other.accountId != null) : !this.accountId.equals(other.accountId)) {
            return false;
        }
        return true;
    }
    
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + (this.appId != null ? this.appId.hashCode() : 0);
        hash = 79 * hash + (this.accountId != null ? this.accountId.hashCode() : 0);
        return hash;
    }
    
    @Override
    public String toString() {
        return "MailAccountPK{" + "appId=" + appId + ", accountId=" + accountId + '}';
    }
    //</editor-fold>
}
